#ifndef IDENTIFIER_H
#define IDENTIFIER_H

enum identifier
{
  INCREMENT_DATA_POINTER = 0,
  DECREMENT_DATA_POINTER = 1,
  INCREMENT_BYTE = 2,
  DECREMENT_BYTE = 3,
  OUTPUT_BYTE = 4,
  INPUT_BYTE = 5,
  MOVE_FORWARD_INSTRUCTION_POINTER = 6,
  MOVE_BACKWARD_INSTRUCTION_POINTER = 7,
  LOOP = 8,
  PROGRAM_START = 9
};

#endif // IDENTIFIER_H